[credentials.usernames.admin]
email = "mktinfo@safeharborequity.com"
name = "Admin"
password = "SHECC1"

[cookie]
expiry_days = 30
key = "1234567A"
name = "shema_auth"

[preauthorized]
emails = ["mktinfo@safeharborequity.com"]
